# Generated by Django 2.1.4 on 2018-12-26 00:16

from django.db import migrations, models
import django.db.models.deletion
import manufacture.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
            ],
            bases=(models.Model, manufacture.models.Description),
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_private', models.BooleanField(default=True)),
                ('manufacture', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='manufacture.Manufacture')),
            ],
            bases=(models.Model, manufacture.models.Description),
        ),
    ]
