# Generated by Django 2.1.5 on 2019-01-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0003_auto_20190110_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacture',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='master',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
