# Generated by Django 2.1.5 on 2019-01-10 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0004_auto_20190110_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacture',
            name='img',
        ),
        migrations.RemoveField(
            model_name='master',
            name='img',
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='metro',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='metro.Metro'),
        ),
        migrations.AlterField(
            model_name='master',
            name='manufacture',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='manufacture.Manufacture'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='master',
            name='metro',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='metro.Metro'),
        ),
    ]
