# Generated by Django 2.1.5 on 2019-01-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0006_auto_20190110_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('multichannel', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='manufacture',
            name='location',
        ),
        migrations.RemoveField(
            model_name='manufacture',
            name='metro',
        ),
        migrations.RemoveField(
            model_name='master',
            name='location',
        ),
        migrations.RemoveField(
            model_name='master',
            name='metro',
        ),
    ]
