# Generated by Django 2.1.5 on 2019-01-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0008_auto_20190124_1243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Number',
        ),
    ]
