# Generated by Django 2.1.5 on 2019-01-24 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0009_delete_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Des',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='manufacture',
            name='id',
        ),
        migrations.AddField(
            model_name='manufacture',
            name='des_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manufacture.Des'),
            preserve_default=False,
        ),
    ]
