# Generated by Django 2.1.5 on 2019-01-24 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0005_auto_20190118_2138'),
        ('manufacture', '0011_auto_20190124_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacture',
            name='adress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manufacture',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacture',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metro.Country'),
        ),
        migrations.AddField(
            model_name='manufacture',
            name='how_get',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacture',
            name='how_search',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacture',
            name='metro',
            field=models.ManyToManyField(to='metro.Metro'),
        ),
        migrations.AddField(
            model_name='manufacture',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacture',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metro.Town'),
        ),
        migrations.AddField(
            model_name='master',
            name='adress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='master',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='master',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metro.Country'),
        ),
        migrations.AddField(
            model_name='master',
            name='how_get',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='master',
            name='how_search',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='master',
            name='metro',
            field=models.ManyToManyField(to='metro.Metro'),
        ),
        migrations.AddField(
            model_name='master',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='master',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metro.Town'),
        ),
    ]
