# Generated by Django 2.1.5 on 2019-01-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0012_auto_20190124_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacture',
            name='login',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacture',
            name='passsword',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='master',
            name='login',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='master',
            name='passsword',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
