# Generated by Django 2.1.5 on 2019-01-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0014_auto_20190125_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacture',
            name='metro',
            field=models.ManyToManyField(blank=True, default=[], null=True, to='metro.Metro'),
        ),
        migrations.AlterField(
            model_name='master',
            name='metro',
            field=models.ManyToManyField(blank=True, default=[], null=True, to='metro.Metro'),
        ),
    ]
