# Generated by Django 2.1.5 on 2019-01-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0015_auto_20190125_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacture',
            name='office',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
