# Generated by Django 2.1.5 on 2019-01-27 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0016_manufacture_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacture',
            name='number',
        ),
        migrations.RemoveField(
            model_name='master',
            name='number',
        ),
        migrations.AddField(
            model_name='number',
            name='manufacture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacture.Manufacture'),
        ),
        migrations.AddField(
            model_name='number',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacture.Master'),
        ),
    ]
