# Generated by Django 2.1.5 on 2019-01-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0017_auto_20190127_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacture',
            name='work_clock_saturday_end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='work_clock_saturday_start',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='work_clock_suday_start',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='work_clock_sunday_end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='work_clock_weekdays_end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='work_clock_weekdays_start',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='work_clock_saturday_end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='work_clock_saturday_start',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='work_clock_suday_start',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='work_clock_sunday_end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='work_clock_weekdays_end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='work_clock_weekdays_start',
            field=models.TimeField(null=True),
        ),
    ]
