# Generated by Django 2.1.5 on 2019-01-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0018_auto_20190127_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacture',
            name='comment_time_work',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='master',
            name='comment_time_work',
            field=models.TextField(blank=True, default=''),
        ),
    ]
