# Generated by Django 2.1.5 on 2019-01-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0019_auto_20190127_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacture',
            old_name='work_clock_suday_start',
            new_name='work_clock_sunday_start',
        ),
        migrations.RenameField(
            model_name='master',
            old_name='work_clock_suday_start',
            new_name='work_clock_sunday_start',
        ),
    ]
