# Generated by Django 2.1.5 on 2019-01-28 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0020_auto_20190127_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacture',
            old_name='passsword',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='master',
            old_name='passsword',
            new_name='password',
        ),
    ]
