# Generated by Django 2.1.4 on 2018-12-28 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0001_initial'),
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='metro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metro.Metro'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.Brand'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='device_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.DeviceModel'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='manufacture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacture.Manufacture'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='manufacture_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacture_service.ManufactureService'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.Mark'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacture.Master'),
        ),
    ]
