# Generated by Django 2.1.5 on 2019-01-10 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0003_auto_20190110_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.Brand'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='device_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.DeviceModel'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.Mark'),
        ),
    ]
