# Generated by Django 2.1.5 on 2019-01-18 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0020_remove_brand_device_type'),
        ('manufacture_service', '0007_auto_20190118_2138'),
        ('proposal', '0004_auto_20190110_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='location',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='name_client',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='manufacture',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='manufacture_service',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='master',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='number_client',
        ),
        migrations.AddField(
            model_name='proposal',
            name='breakage_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacture_service.BreakageAtion'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='device_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.DeviceType'),
        ),
    ]
