# Generated by Django 2.1.5 on 2019-01-22 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture_service', '0007_auto_20190118_2138'),
        ('proposal', '0005_auto_20190118_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='breakage_action',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='mark',
        ),
        migrations.AddField(
            model_name='proposal',
            name='fault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacture_service.Fault'),
        ),
    ]
