# Generated by Django 2.1.5 on 2019-01-27 23:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0006_auto_20190122_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 27, 23, 24, 36, 838267, tzinfo=utc)),
        ),
    ]
