# Generated by Django 2.1.5 on 2019-01-27 23:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0007_proposal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 27, 23, 56, 20, 222556, tzinfo=utc)),
        ),
    ]
