# Generated by Django 2.1.5 on 2019-01-28 01:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0008_auto_20190127_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 28, 1, 49, 59, 674899, tzinfo=utc)),
        ),
    ]
