# Generated by Django 2.1.4 on 2018-12-26 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0002_sparepart'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakageAtion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, max_length=255)),
                ('price', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('translitor', models.CharField(max_length=255)),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Mark')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.SparePart')),
            ],
        ),
        migrations.CreateModel(
            name='ManufactureService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='BreakageAtion',
            name='fault',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacture_service.Fault'),
        ),
        migrations.AddField(
            model_name='BreakageAtion',
            name='manufacture_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacture_service.ManufactureService'),
        ),
    ]
