# Generated by Django 2.1.4 on 2019-01-01 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_sparepart_mark'),
        ('manufacture_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakageation',
            name='mark',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='device.Mark'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='breakageation',
            name='fault',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='manufacture_service.Fault'),
        ),
        migrations.AlterField(
            model_name='breakageation',
            name='link',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='breakageation',
            name='manufacture_service',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='manufacture_service.ManufactureService'),
        ),
        migrations.AlterField(
            model_name='breakageation',
            name='price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
