# Generated by Django 2.1.4 on 2019-01-01 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture_service', '0002_auto_20190101_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='mark',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='device.Mark'),
        ),
        migrations.AlterField(
            model_name='fault',
            name='spare_part',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='device.SparePart'),
        ),
    ]
