# Generated by Django 2.1.5 on 2019-01-10 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture_service', '0005_auto_20190110_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakageation',
            name='fault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacture_service.Fault'),
        ),
        migrations.AlterField(
            model_name='breakageation',
            name='manufacture_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacture_service.ManufactureService'),
        ),
        migrations.AlterField(
            model_name='breakageation',
            name='mark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.Mark'),
        ),
        migrations.AlterField(
            model_name='fault',
            name='mark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.Mark'),
        ),
    ]
