# Generated by Django 2.1.5 on 2019-01-18 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0007_auto_20190118_2138'),
        ('manufacture_service', '0006_auto_20190110_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakageation',
            name='manufacture_service',
        ),
        migrations.RemoveField(
            model_name='breakageation',
            name='price',
        ),
        migrations.RemoveField(
            model_name='manufactureservice',
            name='name',
        ),
        migrations.AddField(
            model_name='manufactureservice',
            name='breaking_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacture_service.BreakageAtion'),
        ),
        migrations.AddField(
            model_name='manufactureservice',
            name='manufacture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacture.Manufacture'),
        ),
        migrations.AddField(
            model_name='manufactureservice',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacture.Master'),
        ),
        migrations.AddField(
            model_name='manufactureservice',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
