# Generated by Django 2.1.5 on 2019-01-27 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0021_mark_brand'),
        ('manufacture_service', '0007_auto_20190118_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufactureservice',
            name='mark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.Mark'),
        ),
    ]
