# Generated by Django 2.1.4 on 2018-12-30 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20181229_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_model',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='device',
            name='mark',
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='brand',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='device.Brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/device/img'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='mark',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='device.Mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='series',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='translitor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='type',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='device.DeviceType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='year',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='translitor',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
