# Generated by Django 2.1.4 on 2018-12-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_auto_20181230_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
