# Generated by Django 2.1.4 on 2018-12-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_auto_20181230_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='series',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='translitor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='year',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
