# Generated by Django 2.1.4 on 2019-01-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_sparepart_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepart',
            name='mark',
        ),
    ]
