# Generated by Django 2.1.4 on 2019-01-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0011_auto_20190101_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='translitor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
