# Generated by Django 2.1.5 on 2019-01-10 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0012_auto_20190104_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAffiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='devicetype',
            name='device_afilication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.DeviceAffiliation'),
        ),
    ]
