# Generated by Django 2.1.5 on 2019-01-10 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0017_auto_20190110_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.DeviceType'),
        ),
    ]
