# Generated by Django 2.1.5 on 2019-01-18 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0019_auto_20190110_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='device_type',
        ),
    ]
