# Generated by Django 2.1.5 on 2019-01-19 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0020_remove_brand_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.Brand'),
        ),
    ]
