# Generated by Django 2.1.5 on 2019-01-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0002_metro_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='metro',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
